services:
  - type: web
    name: ai-interview-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # <- this tells Render to expect a value from the dashboard
